#!/bin/sh

NIXOS_VERSION=${NIXOS_VERSION:-20.03}
export NIX_PATH=nixpkgs=https://github.com/NixOS/nixpkgs-channels/archive/nixos-${NIXOS_VERSION}.tar.gz
export NIXOPS_DEPLOYMENT=luffy
export NIXOPS_STATE=state.nixops

exec nix run nixpkgs.nixops -c nixops "$@"

# Local Variables:
# mode: sh
# End:
